Changed logger variable name due to variable name conflict picked up by gfortran in CI
> Error: The type 'logger' cannot be host associated at (1) because it
> is blocked by an incompatible object of the same name declared at (2)