Add travis CI (#44)
Added .travis.yml

Turned on verbose make in oasis

Restoring recent CMake changes

Altered build.sh to make sure CMake status is correctly returned

Change to standard gfortran and gcc for libnetcdff compatibility

Changed logger variable name due to variable name conflict picked up
by gfortran in CI

> Error: The type 'logger' cannot be host associated at (1) because it
> is blocked by an incompatible object of the same name declared at (2)

Fixed long lines

Changed non-standard inquire call

Change to flush statement

Added automatic deployment of releases for tagged branches

Updated CI badges in README